// MARK: - AutoCompletion

#if compiler(>=6.0)
{% for type in types.protocols|annotated:"AutoCompletion" %}

extension {{ type.name }} {
    {% for method in type.methods %}
        {% if not method.isAsync and not method.throws %}
            {% continue %}
        {% endif %}

    {% for documentation in method.documentation %}
    /// {{ documentation }}
    {% endfor %}
    @available(*, deprecated, message: "Use the async method instead.")
    {% for key, value in method.attributes %}
    {% if key == "preconcurrency" %}
        {% break %}
    {% endif %}
    {{ value.first }}
    {% endfor %}
    @preconcurrency
    @discardableResult
    public func {{ method.callName }}(
        {% for parameter in method.parameters %}
        {{ parameter.asSource }},
        {% endfor %}
        completion: sending @escaping @isolated(any) (Result<{{ method.returnTypeName.asSource }}, POFailure>) -> Void
    ) -> POCancellable {
        invoke(completion: completion) {
            try await {{ method.callName }}({% for parameter in method.parameters %}{% if parameter.argumentLabel %}{{ parameter.argumentLabel }}: {% endif %}{{ parameter.name }}{% if not forloop.last %}, {% endif %}{% endfor %})
        }
    }
    {% endfor %}
}
{% if forloop.last %}

/// Invokes given completion with a result of async operation.
private func invoke<T>(
    completion: sending @escaping @isolated(any) (Result<T, POFailure>) -> Void,
    withResultOf operation: @escaping @MainActor () async throws -> T
) -> POCancellable {
    Task { @MainActor in
        do {
            let returnValue = try await operation()
            await completion(.success(returnValue))
        } catch let failure as POFailure {
            await completion(.failure(failure))
        } catch {
            let failure = POFailure(message: "Something went wrong.", code: .Mobile.internal, underlyingError: error)
            await completion(.failure(failure))
        }
    }
}

#endif
{% endif %}
{% endfor %}
